### ISSUE TITLE
DiscretePOMDP should use rng

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPModels.jl#11]
Hi @etotheipluspi,

Was looking working on GridWorlds and I noticed the Discrete problem - seems really useful; thanks for making that. I did find one misleading thing though: Right now `DiscreteDistribution` has `rand(rng::AbstractRNG, d::DiscreteDistribution, s::Int64)`, but it uses the global random number generator rather than `rng`, which will make it more difficult to reproduce results exactly. This is also true for `StateDistribution`. It should be easy to fix by using WeightVec from POMDPToolbox instead of Categorical.

**Comment by mykelk** [comment]
Should this be fixed?

**Comment by etotheipluspi** [comment]
This sounds good to me!
