### ISSUE TITLE
Cannot precompile the package

### ISSUE THREAD

**Issue by AStupidBear** [JuliaPOMDP/POMDPModels.jl#19]
```julia
using POMDPModels
```
```


INFO: Precompiling module POMDPModels.
ERROR: LoadError: LoadError: TypeError: Type{...} expression: expected UnionAll, got Type{POMDPs.Updater}
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:569
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:569
 [4] include(::String) at ./sysimg.jl:14
 [5] anonymous at ./<missing>:2
while loading /home/juser/.julia/v0.6/POMDPToolbox/src/beliefs/void.jl, in expression starting on line 4
while loading /home/juser/.julia/v0.6/POMDPToolbox/src/POMDPToolbox.jl, in expression starting on line 36
ERROR: LoadError: Failed to precompile POMDPToolbox to /home/juser/.julia/lib/v0.6/POMDPToolbox.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:703
 [2] _require(::Symbol) at ./loading.jl:456
 [3] require(::Symbol) at ./loading.jl:398
 [4] include_from_node1(::String) at ./loading.jl:569
 [5] include(::String) at ./sysimg.jl:14
 [6] anonymous at ./<missing>:2
while loading /home/juser/.julia/v0.6/POMDPModels/src/POMDPModels.jl, in expression starting on line 13
Failed to precompile POMDPModels to /home/juser/.julia/lib/v0.6/POMDPModels.ji.

Stacktrace:
 [1] compilecache(::String) at ./loading.jl:703
 [2] _require(::Symbol) at ./loading.jl:490
 [3] require(::Symbol) at ./loading.jl:398
```

I had a one day project and failed to precompile this package after reading the lengthy tutorial.  I'm disappointed and depressed.

**Comment by zsunberg** [comment]
Hi Yao, I'm sorry that you have been having trouble with it. Is it fixed if you run `Pkg.free("POMDPs"); Pkg.update()`? We have been making some recent changes that could affect the TypeError that you are getting.

If that doesn't work, can you send the output of the following commands:
```julia
Pkg.installed("POMDPs")
Pkg.installed("POMDPModels")
Pkg.installed("POMDPToolbox")
```

Thanks!

**Comment by AStupidBear** [comment]
It works, thanks!

**Comment by AStupidBear** [comment]
But I cannot precompile MCTS.jl for Julia 0.5.2.

**Comment by zsunberg** [comment]
Hi Yao, Do you need it to work with Julia 0.5? Right now, the master branches of the solvers only work on 0.6. If you definitely need to use 0.5, we can create a tag of MCTS that is compatible with 0.5.

- Zach

**Comment by AStupidBear** [comment]
Hi Zach, I do need a version of  MCTS.jl that's compatible with Julia 0.5 because I'm combining Deep Neural Network and MCTS to create an AlphaGo like system for the Reversi game but Knet.jl doesn't support Julia 0.6. I would appreciate it if you can tag a new version.

**Comment by zsunberg** [comment]
Hi Yao, Cool! I am interested to see how that alpha-go-like system turns out. I tagged a version of MCTS with 0.5 compatibility and called it v0.1.2, so if you navigate to the MCTS package directory and do `git fetch --all --tags` and then `git checkout v0.1.2`, I think it will work. FYI, There is also a git branch of MCTS called "fast" that is faster for simple problems, but doesn't support tree visualization.

Good luck!

- Zach

**Comment by AStupidBear** [comment]
Thanks！
