### ISSUE TITLE
RockSample 

### ISSUE THREAD

**Issue by MaximeBouton** [JuliaPOMDP/POMDPModels.jl#24]
Shouldn't the rock sample implementation here: https://github.com/JuliaPOMDP/DESPOT.jl/tree/master/src/problems/RockSample
be moved to POMDPModels.jl? 

Most of the solver are benchmarked using the rock sample problem, it would be nice to have it implemented.

**Comment by zsunberg** [comment]
Yeah, it would be great to have a well-maintained and easy-to-find version of it! I think we should put most problems in their own repositories, but RockSample is well-established enough to put in POMDPModels.

I haven't looked at it in a while, but IIRC I think the implementation in DESPOT needs some cleanup/modernization before putting it in POMDPModels. We don't want to have to change it later.

**Comment by MaximeBouton** [comment]
Sounds good, I will leave this issue open and try to take a look at it in the near future

**Comment by MaximeBouton** [comment]
https://github.com/JuliaPOMDP/RockSample.jl
