### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by sharabhs** [JuliaPOMDP/POMDPModels.jl#27]
Any help, I am getting the following error message while attempting to install the package??

Pkg.add("POMDPModels")
ERROR: resolve is unable to satisfy package requirements.
  The problem was detected when trying to find a feasible version
  for package Graphs.
  However, this only means that package Graphs is involved in an
  unsatisfiable or difficult dependency relation, and the root of
  the problem may be elsewhere.

resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}) at .\pkg\resolve.jl:48
resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}, ::Dict{String,VersionNumber}, ::Set{String}) at .\pkg\entry.jl:499
resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}) at .\pkg\entry.jl:479
edit(::Function, ::String, ::Base.Pkg.Types.VersionSet, ::Vararg{Base.Pkg.Types.VersionSet,N} where N) at .\pkg\entry.jl:30
(::Base.Pkg.Entry.##1#3{String,Base.Pkg.Types.VersionSet})() at .\task.jl:335
Stacktrace:
 [1] sync_end() at .\task.jl:287
 [2] macro expansion at .\task.jl:303 [inlined]
 [3] add(::String, ::Base.Pkg.Types.VersionSet) at .\pkg\entry.jl:51
 [4] (::Base.Pkg.Dir.##4#7{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}})() at .\pkg\dir.jl:36
 [5] cd(::Base.Pkg.Dir.##4#7{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}}, ::String) at .\file.jl:59
 [6] #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{String,N} where N) at .\pkg\dir.jl:36
 [7] add(::String) at .\pkg\pkg.jl:117
 [8] eval(::Module, ::Any) at .\boot.jl:235

**Comment by zsunberg** [comment]
Sorry you're having trouble. Graphs.jl is fairly old, so it may have dependences that can't be reconciled with POMDPModels. You may need to uninstall it (I think LightGraphs.jl is more actively maintained if you need a graph package).

What is the output of 
```
julia> versioninfo()
```
and
```
julia> for (p,v) in Pkg.installed()
       println("$v\t[$p]")
       end
```
on your machine?

**Comment by sharabhs** [comment]
HI,

I really appreciate you making your package open source and thanks for taking out time to address my problem.

versioninfo()

Julia Version 0.6.2
Commit d386e40c17* (2017-12-13 18:08 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Prescott)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)

& 

.2.4   [Libz]
0.7.3   [ForwardDiff]
0.5.0   [GLPK]
0.0.0-  [MCTS]
0.2.0   [AxisAlgorithms]
0.0.0-  [POMDPSolve]
0.4.0   [Juno]
0.1.4   [OSQP]
0.2.3   [ConicBenchmarkUtilities]
0.0.4   [Nullables]
0.7.4   [DataStructures]
0.61.0  [Compat]
0.2.2   [Calculus]
0.3.0   [GZip]
0.7.0   [MathProgBase]
0.1.0   [Measures]
0.2.0   [ShowItLikeYouBuildIt]
0.0.0-  [SARSOP]
0.2.3   [RecipesBase]
0.5.0   [StatsFuns]
0.4.0   [JuMPChance]
0.5.1   [Cairo]
0.0.1   [CoupledFields]
0.10.1  [DataFrames]
0.8.0   [ECOS]
0.6.6   [POMDPs]
0.3.8   [SpecialFunctions]
0.4.3   [Requires]
0.3.0   [Blosc]
0.1.1   [Showoff]
0.15.0  [Distributions]
0.4.1   [LibExpat]
0.4.6   [FixedPointNumbers]
0.0.0-  [ARDESPOT]
0.5.6   [SHA]
0.3.0   [DualNumbers]
0.2.7   [Missings]
0.8.1   [ReverseDiffSparse]
0.3.0   [Media]
0.4.1   [KernelDensity]
0.8.8   [HDF5]
0.6.7   [ColorTypes]
0.3.1   [Iterators]
0.4.0   [BufferedStreams]
0.2.1   [Polynomials]
0.5.5   [ProgressMeter]
0.6.5   [Gadfly]
0.7.0   [FileIO]
0.3.3   [Gurobi]
0.2.0   [PlotThemes]
0.4.0   [Contour]
0.8.0   [PDMats]
0.0.0-  [DESPOT]
0.14.0  [Optim]
0.2.0   [SortingAlgorithms]
0.3.2   [CPLEX]
0.3.1   [WinRPM]
0.4.0   [AmplNLWriter]
0.0.1   [CommonSubexpressions]
0.4.4   [PlotUtils]
0.2.2   [WoodburyMatrices]
0.17.1  [JSON]
0.20.1  [StatsBase]
0.3.3   [SCS]
0.1.0   [Hexagons]
0.5.0   [Distances]
0.15.0  [Plots]
0.3.0   [Loess]
4.3.0   [NLSolversBase]
0.2.0   [QuadGK]
0.7.0   [StaticArrays]
0.8.7   [BinDeps]
0.6.0   [Xpress]
0.1.0   [PositiveFactorizations]
0.8.1   [Parameters]
0.4.0   [DiffEqDiffTools]
0.2.0   [Rainflow]
0.1.0   [Reexport]
0.2.0   [Graphics]
0.3.1   [NaNMath]
0.3.1   [URIParser]
0.0.0-  [GenerativeModels]
0.0.0-  [FIB]
0.3.2   [Rmath]
0.7.3   [Interpolations]
0.2.5   [BinaryProvider]
0.18.0  [JuMP]
0.3.0   [ControlSystems]
0.0.3   [DiffResults]
0.2.1   [IterTools]
3.2.5   [LineSearches]
0.3.0   [Ipopt]
0.5.5   [Compose]
0.6.2   [DataArrays]
0.1.3   [ConicNonlinearBridge]
0.0.3   [DiffRules]
0.8.2   [Colors]
0.5.0   [Pajarito]
0.4.0   [MacroTools]
0.2.4   [POMDPToolbox]
0.0.0-  [ContinuumWorld]
0.2.0   [Ratios]
0.8.3   [Mosek]

**Comment by sharabhs** [comment]
I think there might be problem with my julia installation, I am unable to install even any other packages. I get the same error even if I do Pkg.update().

I am trying to delete everything and put a fresh installation, lets see if that works.

**Comment by zsunberg** [comment]
Yeah, unfortunately that may be the easiest way.

I think I see some clues: DataFrames had a breaking change between v0.10 and v0.11 so you probably have a package that is holding it back. Having DataFrames v0.10 holds a lot of packages back. For instance the latest tagged POMDPToolbox (v0.2.6) requires DataFrames v0.11.

Hope you can get it figured out! If you want to start from scratch make sure you delete (make a backup though!) the directory that is output by
```
julia> Pkg.dir()
```

**Comment by sharabhs** [comment]
Hi,

Fresh installation does away with the problem in this module but I see some other problems in solvers. 

I am okay with closing this issue for now.

**Comment by sharabhs** [comment]
And I think its the "Gadfly.jl" package that leads to this breakage. The moment I tried installing Gadfly, I gain encountered the same problem.

**Comment by zsunberg** [comment]
Ok, yeah thanks for the note about Gadfly - that may be useful to others. Hope you can get the solvers working!
