### ISSUE TITLE
DiscreteMDP more general abstract type

### ISSUE THREAD

**Issue by dominusmi** [JuliaPOMDP/POMDPModels.jl#38]
Hi everyone,

I've been working with POMDPs for a while now, at the moment I'm implementing a "GraphMDP" which creates and MDP from graphs (defined using LightGraphs).
Using this, I tried to see if I could fit it in `DiscreteMDP`, with which I've got a few issues:

- I believe DiscreteMDP should be an abstract type, since it's a general concept, and should only include the requirement of states and actions being discrete and iterable 
_[EDIT: just noticed part of this point is already mentioned in #28 ]_

- The current way the transition matrix works is very wasteful, since it assumes any state can go to any states, and doesn't use a sparse matrix to do so ( a relatively small MDP of a 1000 states and 4 actions already yields a 1000 x 4 x 1000 large matrix). This could be replaced with an abstract type such as `AbstractMatrix`
 
- The type doesn't include a variable containing the terminal state(s)

I'm pretty much fixing these issues as I go (for personal use), so I'm wondering if you agree with the ideas I've put forth and whether I should do PR once I'm finished.

Have a good day!

**Comment by zsunberg** [comment]
Hi @dominusmi , thanks for the insights!

> I believe DiscreteMDP should be an abstract type, since it's a general concept, and should only include the requirement of states and actions being discrete and iterable
[EDIT: just noticed part of this point is already mentioned in #28 ]

1. Yeah, DiscreteMDP is definitely a poor name for that model. We'll rename it to TabularMDP for the julia-1.0-compatible release (I have already fixed this: #39).

> The current way the transition matrix works is very wasteful, since it assumes any state can go to any states, and doesn't use a sparse matrix to do so ( a relatively small MDP of a 1000 states and 4 actions already yields a 1000 x 4 x 1000 large matrix). This could be replaced with an abstract type such as AbstractMatrix

2. Yes, it should be replaced with abstract matrices.

> The type doesn't include a variable containing the terminal state(s)

3. I guess we could have a (sparse) bit array that indicates whether a state is terminal.

We are kind of blocked up right now with registering packages in METADATA, but once this package is registered for julia-1.0, would you like to make a PR to fix 2 and 3, or should I make the changes eventually?

Concerning a DiscreteMDP abstract type - I don't think it would actually be very useful. There are many problems where the action space is discrete but the state space is continuous, for example. A better approach would be to have some sort of traits that allow the programmer to determine whether each space is discrete or continuous. This would take some design work, and it is not clear what mechanisms Julia will adopt for this. Moreover, in the future we hope to have some way of representing factorization and mixed observability (MOMDPs), so we want to keep the type hierarchy as lean as possible.

**Comment by dominusmi** [comment]
I'm happy to make the changes when the time comes, realistically they're already implemented, just need to make sure it's not using deprecated syntax since I'm still working on 0.6.

Regarding 3, I'm currently using a dictionary, but I think you're right in using a bit array since we states must be iterable meaning we know that whatever type the state actually is, we can access it through an integer index. Dictionaries require the state to be "hashable",  however they may (or may not, not an expert) have a performance boost? 

Regarding the last paragraph, that's way above my knowledge so I'll you on it!

**Comment by zsunberg** [comment]
Hey @dominusmi , the changes for julia 0.7/1.0 for this package have been merged into master, so if you would like to take a stab at these changes and submit a pull request, it's ready for you!

**Comment by dominusmi** [comment]
Currently writing my MSc thesis which needs to handed out monday, I'll give it a go next week as soon as I'm finished!
