### ISSUE TITLE
RandomPolicy definitions missing

### ISSUE THREAD

**Issue by rguptatx** [JuliaPOMDP/POMDPModels.jl#4]
RandomPolicy is not defined in POMDPToolbox.jl

Where can i find it?

**Comment by etotheipluspi** [comment]
```RandomPolicy``` should be part of POMDPToolbox. You can find the RandomPolicy file [here](https://github.com/JuliaPOMDP/POMDPToolbox.jl/blob/master/src/policies/random.jl).
