### ISSUE TITLE
Running /src/GridWorlds.jl and /test/gridworld.jl doesn't recognize actions

### ISSUE THREAD

**Issue by Divide-By-0** [JuliaPOMDP/POMDPModels.jl#5]
After running the test file, I get this error:
```
LoadError: POMDPs.jl: No implementation of actions for problem::GridWorld.
while loading In[7], in expression starting on line 358

 in error at ./error.jl:21
```
where line 358 refers to:
`policy = RandomPolicy(problem)`
However, the actions are defined.

edit: clarified error

**Comment by zsunberg** [comment]
Thanks for reporting the issue! I assume that you ran `include("src/GridWorlds.jl")`. We didn't design the file GridWorlds.jl to work like this. Instead, please import the package with `using POMDPModels` or `import POMDPModels`. That should avoid the issue.

If this doesn't fix the error, please let us know
